Downloading the Dataset

In [2]:
!kaggle datasets download -d mlg-ulb/creditcardfraud

Dataset URL: https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud
License(s): DbCL-1.0
 83% 55.0M/66.0M [00:00<00:00, 128MB/s]
100% 66.0M/66.0M [00:00<00:00, 96.6MB/s]


Unzipping the zip folder

In [3]:
!unzip /content/creditcardfraud.zip -d my_data

Archive:  /content/creditcardfraud.zip
  inflating: my_data/creditcard.csv  


Importing the dependencies

In [40]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,f1_score,confusion_matrix,precision_score,recall_score
from sklearn.preprocessing import StandardScaler

Loading the dataset to pandas frame

In [41]:
df=pd.read_csv('/content/my_data/creditcard.csv')

In [42]:
df.head(5) #first 5 rows

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [43]:
df.tail(5) #last 5 rows

Time         V1         V2        V3        V4        V5  \
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[5 rows x 31 columns]

In [44]:
df.info() #information about dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

In [45]:
#checking for numbers of missing values
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [46]:
df['Class'].value_counts() #check for distribution of normal and fraud transactions

Class
0    284315
1       492
Name: count, dtype: int64

Dataset is highly unbalanced


0 --> Normal


1 --> Fraudalent

In [47]:
#sepearting the data for analysis
legit=df[df['Class']==0]
fraud=df[df['Class']==1]

In [48]:
print(legit.shape)

(284315, 31)


In [49]:
print(fraud.shape)

(492, 31)


In [50]:
#stats information of legit data
print(legit['Amount'].describe())

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64


In [51]:
#stats information of fraud data
print(fraud['Amount'].describe())

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64


In [52]:
#Comparing for both transaction
df.groupby('Class').mean()

Time        V1        V2        V3        V4        V5  \
Class                                                                   
0      94838.202258  0.008258 -0.006271  0.012171 -0.007860  0.005453   
1      80746.806911 -4.771948  3.623778 -7.033281  4.542029 -3.151225   

             V6        V7        V8        V9  ...       V20       V21  \
Class                                          ...                       
0      0.002419  0.009637 -0.000987  0.004467  ... -0.000644 -0.001235   
1     -1.397737 -5.568731  0.570636 -2.581123  ...  0.372319  0.713588   

            V22       V23       V24       V25       V26       V27       V28  \
Class                                                                         
0     -0.000024  0.000070  0.000182 -0.000072 -0.000089 -0.000295 -0.000131   
1      0.014049 -0.040308 -0.105130  0.041449  0.051648  0.170575  0.075667   

           Amount  
Class              
0       88.291022  
1      122.211321  

[2 rows x 30 columns]

Handling unbalanced data using Under-Sampling

Building a sample dataset containing similar distribution

492 fraud

In [53]:
legit_sample=legit.sample(n=492)

In [54]:
#concating two dataframe
new_df=pd.concat([legit_sample,fraud],axis=0)

In [55]:
new_df

Time        V1        V2        V3        V4        V5        V6  \
237690  149351.0  1.899296 -0.290465 -1.342068  0.032259  0.748507  0.911224   
108903   71126.0 -1.196672  1.446840  2.305700  2.771612 -0.808658  0.995768   
5434      5423.0 -1.240744  1.215489  2.042497  0.697227  0.233118  2.036400   
99255    67037.0  1.345138 -0.287263 -0.515059 -1.855017  0.193098  0.018421   
8434     11309.0 -1.297011  2.143955  1.371955  2.807134 -0.477587  0.578798   
...          ...       ...       ...       ...       ...       ...       ...   
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494   
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536   
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346   
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548   
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695   

              V7        V8        V9  ...       V21       V22       V23  \
237690 -0.168297  0.287678  0.295527  ... -0.174590 -0.304281  0.357632   
108903 -0.616333  0.979612 -0.739148  ... -0.042711  0.005383 -0.200620   
5434   -0.474839  1.185866  0.465522  ...  0.020466  0.379057 -0.007065   
99255  -0.140863  0.057199  0.972138  ... -0.199859 -0.476161 -0.113990   
8434   -0.179430  0.846983 -0.402461  ... -0.299375 -0.832004 -0.051560   
...          ...       ...       ...  ...       ...       ...       ...   
279863 -0.882850  0.697211 -2.064945  ...  0.778584 -0.319189  0.639419   
280143 -1.413170  0.248525 -1.127396  ...  0.370612  0.028234 -0.145640   
280149 -2.234739  1.210158 -0.652250  ...  0.751826  0.834108  0.190944   
281144 -2.208002  1.058733 -1.632333  ...  0.583276 -0.269209 -0.456108   
281674  0.223050 -0.068384  0.577829  ... -0.164350 -0.295135 -0.072173   

             V24       V25       V26       V27       V28  Amount  Class  
237690 -1.500416 -0.502101  0.303385 -0.022859 -0.084667    8.99      0  
108903 -0.014922  0.103988  0.271855  0.350574  0.133268    9.49      0  
5434   -1.097740 -0.127577 -0.286479  0.262129  0.061607   18.86      0  
99255  -1.321896  0.507309 -0.026579  0.001292 -0.014569    1.88      0  
8434   -0.550586  0.084037  0.048996 -0.055000  0.004801   53.25      0  
...          ...       ...       ...       ...       ...     ...    ...  
279863 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00      1  
280143 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76      1  
280149  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89      1  
281144 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00      1  
281674 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53      1  

[984 rows x 31 columns]

In [56]:
new_df['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [57]:
new_df.groupby('Class').mean() ## similar distribution as of df

Time        V1        V2        V3        V4        V5  \
Class                                                                   
0      90363.144309  0.135188 -0.165789  0.054325 -0.013306  0.019109   
1      80746.806911 -4.771948  3.623778 -7.033281  4.542029 -3.151225   

             V6        V7        V8        V9  ...       V20       V21  \
Class                                          ...                       
0     -0.005175 -0.036897 -0.055495 -0.043788  ...  0.062323 -0.026688   
1     -1.397737 -5.568731  0.570636 -2.581123  ...  0.372319  0.713588   

            V22       V23       V24       V25       V26       V27       V28  \
Class                                                                         
0     -0.050678  0.001003 -0.001658  0.011451  0.028359 -0.012554 -0.004661   
1      0.014049 -0.040308 -0.105130  0.041449  0.051648  0.170575  0.075667   

           Amount  
Class              
0       97.614614  
1      122.211321  

[2 rows x 30 columns]

Splitting the data into labels and features

In [58]:
 X=new_df.drop(columns='Class',axis=1)
 y=new_df['Class']

In [59]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
237690  149351.0  1.899296 -0.290465 -1.342068  0.032259  0.748507  0.911224   
108903   71126.0 -1.196672  1.446840  2.305700  2.771612 -0.808658  0.995768   
5434      5423.0 -1.240744  1.215489  2.042497  0.697227  0.233118  2.036400   
99255    67037.0  1.345138 -0.287263 -0.515059 -1.855017  0.193098  0.018421   
8434     11309.0 -1.297011  2.143955  1.371955  2.807134 -0.477587  0.578798   
...          ...       ...       ...       ...       ...       ...       ...   
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494   
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536   
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346   
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548   
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695   

              V7        V8        V9  .

In [60]:
print(y)

237690    0
108903    0
5434      0
99255     0
8434      0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64


Splitting the data into train and testing data

Startify -- to evenly distribute on basis of labels

In [61]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,stratify=y,random_state=2)

In [62]:
print(X.shape,X_train.shape,X_test.shape)

(984, 30) (787, 30) (197, 30)


Scaling the Data with mean=0 and std=1

In [63]:
scaler=StandardScaler()
scaler.fit(X_train)
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

In [64]:
X_train[:5]

array([[-3.80098025e-01,  2.76819596e-01, -4.66146878e-01,
         5.39711797e-01, -1.11745950e+00, -9.93699094e-02,
         8.37216912e-01,  1.00737479e+00, -1.53475862e-01,
         8.44602903e-01,  2.28450571e-01, -9.26873549e-01,
         6.82441392e-01, -4.69503245e-01,  7.97852083e-01,
         9.49796095e-01,  2.51248001e-01,  5.98310689e-01,
         3.05431408e-01,  2.80212660e-01, -2.23651434e-01,
        -1.11465146e-01,  3.80654273e-01,  8.21239058e-02,
        -3.49976950e-01,  7.95074701e-01, -1.18340019e+00,
         6.57235405e-02, -3.99386420e-01,  1.57228120e+00],
       [-1.72071160e+00,  6.33456819e-01, -4.11122380e-01,
         6.45480669e-01, -4.66623011e-01,  2.17406393e-01,
        -2.56233586e-01,  5.00358021e-01, -1.15360398e-01,
         5.46319585e-01,  6.11675909e-01, -6.63654002e-01,
         8.29368386e-01,  7.17260307e-01,  7.85617522e-01,
         9.60650946e-01,  6.14813624e-01,  5.03794094e-01,
         2.68848184e-01, -5.78604342e-01, -1.96093993e-

Model training:

Logistic Regression : for binary classification

In [65]:
model=LogisticRegression()

In [66]:
model.fit(X_train,y_train)

LogisticRegression()

Model evaluation

Accuracy Score

In [67]:
#accuracy on training  data
X_train_pred=model.predict(X_train)
training_data_accuracy=accuracy_score(X_train_pred,y_train)
print(f"Train accuracy: {training_data_accuracy*100} percent")

Train accuracy: 95.1715374841169 percent


In [68]:
#accuracy on test data
X_test_pred=model.predict(X_test)
test_data_accuracy=accuracy_score(X_test_pred,y_test)
print(f"Test accuracy: {test_data_accuracy*100} percent")

Test accuracy: 94.41624365482234 percent


In [69]:
confusion_matrix(X_test_pred,y_test)

array([[98, 10],
       [ 1, 88]])

Comapring different model

Training and predict test accuracy

In [74]:
classifier={
    'LogisticRegression':LogisticRegression(),
    'DecisionTreeClassifier':DecisionTreeClassifier(),
    'RandomForestClassifier':RandomForestClassifier(n_estimators=100)
}
for name,clf in classifier.items():
  print("Training the",name,"...")
  clf.fit(X_train,y_train)
  y_pred=clf.predict(X_test)
  print(f"\n {name} accuracy: {accuracy_score(y_pred,y_test)*100} percent")
  print(f"\n {name} precision: {precision_score(y_pred,y_test)*100} percent")
  print(f"\n {name} recall: {precision_score(y_pred,y_test)*100} percent")
  print(f"\n {name} f1_score: {f1_score(y_pred,y_test)*100} percent")
  print(f"\n {name} confusion_matrix:\n {confusion_matrix(y_pred,y_test)}")


Training the LogisticRegression ...

 LogisticRegression accuracy: 94.41624365482234 percent

 LogisticRegression precision: 89.79591836734694 percent

 LogisticRegression recall: 89.79591836734694 percent

 LogisticRegression f1_score: 94.11764705882354 percent

 LogisticRegression confusion_matrix:
 [[98 10]
 [ 1 88]]
Training the DecisionTreeClassifier ...

 DecisionTreeClassifier accuracy: 91.87817258883248 percent

 DecisionTreeClassifier precision: 90.81632653061224 percent

 DecisionTreeClassifier recall: 90.81632653061224 percent

 DecisionTreeClassifier f1_score: 91.75257731958763 percent

 DecisionTreeClassifier confusion_matrix:
 [[92  9]
 [ 7 89]]
Training the RandomForestClassifier ...

 RandomForestClassifier accuracy: 93.4010152284264 percent

 RandomForestClassifier precision: 86.73469387755102 percent

 RandomForestClassifier recall: 86.73469387755102 percent

 RandomForestClassifier f1_score: 92.89617486338798 percent

 RandomForestClassifier confusion_matrix:
 [[99 1

Handling unbalanced data using Over-Sampling

Building a sample dataset containing similar distribution

In [75]:
X=df.drop(columns='Class',axis=1)
y=df['Class']

In [77]:
X.shape

(284807, 30)

In [78]:
from imblearn.over_sampling import SMOTE
smote=SMOTE()
X_res,y_res=smote.fit_resample(X,y) #oversampling

In [79]:
y_res.value_counts()

Class
0    284315
1    284315
Name: count, dtype: int64

In [81]:
X_train, X_test, y_train, y_test = train_test_split(X_res,y_res,test_size=0.2,stratify=y_res,random_state=2)

In [82]:
scaler=StandardScaler()
scaler.fit(X_train)
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

In [83]:
classifier={
    'LogisticRegression':LogisticRegression(),
    'DecisionTreeClassifier':DecisionTreeClassifier(),
    'RandomForestClassifier':RandomForestClassifier(n_estimators=100)
}
for name,clf in classifier.items():
  print("Training the",name,"...")
  clf.fit(X_train,y_train)
  y_pred=clf.predict(X_test)
  print(f"\n {name} accuracy: {accuracy_score(y_pred,y_test)*100} percent")
  print(f"\n {name} precision: {precision_score(y_pred,y_test)*100} percent")
  print(f"\n {name} recall: {precision_score(y_pred,y_test)*100} percent")
  print(f"\n {name} f1_score: {f1_score(y_pred,y_test)*100} percent")
  print(f"\n {name} confusion_matrix:\n {confusion_matrix(y_pred,y_test)}")


Training the LogisticRegression ...


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(



 LogisticRegression accuracy: 98.04354325308196 percent

 LogisticRegression precision: 96.92418620192392 percent

 LogisticRegression recall: 96.92418620192392 percent

 LogisticRegression f1_score: 98.0213956052751 percent

 LogisticRegression confusion_matrix:
 [[56387  1749]
 [  476 55114]]
Training the DecisionTreeClassifier ...

 DecisionTreeClassifier accuracy: 99.8382076218279 percent

 DecisionTreeClassifier precision: 99.91558658530153 percent

 DecisionTreeClassifier recall: 99.91558658530153 percent

 DecisionTreeClassifier f1_score: 99.83833271829475 percent

 DecisionTreeClassifier confusion_matrix:
 [[56727    48]
 [  136 56815]]
Training the RandomForestClassifier ...

 RandomForestClassifier accuracy: 99.98593109755025 percent

 RandomForestClassifier precision: 100.0 percent

 RandomForestClassifier recall: 100.0 percent

 RandomForestClassifier f1_score: 99.98593307661197 percent

 RandomForestClassifier confusion_matrix:
 [[56847     0]
 [   16 56863]]


Fitting the best model on entire data

In [86]:
final_model=RandomForestClassifier(n_estimators=10)
final_model.fit(X_res,y_res)

RandomForestClassifier(n_estimators=10)

Saving the model

In [87]:
import joblib
joblib.dump(final_model,"credit_card_fraud_detection.pkl")

['credit_card_fraud_detection.pkl']

Making prediction on single data

In [92]:
pred=final_model.predict([[-0.13812877,  0.38467115, -0.36717439,  0.603599  , -1.21753794,
        0.59132788,  0.79295263,  0.70346362, -0.06431267,  0.58920284,
        0.44062342, -0.58898655,  0.88753858,  0.75246818,  0.90314929,
        1.54558954,  0.39029109,  0.52365283,  0.62664894,  1.83958881,
       -0.05373192, -0.23619368, -0.6100036 , -0.13271957, -3.07818891,
       -0.28929716, -1.9315189 ,  0.01367331,  0.15531727,  0.01863647]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [93]:
if pred==0:
  print("Normal Transaction")
else:
  print("Fraudlent Transaction")

Normal Transaction
